name: 'Update LICENSES.md'

on:
  workflow_dispatch:
  push:
    paths:
      - 'Cargo.lock'

permissions:
  contents: write

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -eo pipefail {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.8.0

      - name: Install cargo-about
        run: cargo install cargo-about

      - name: Generate LICENSES.md
        run: cargo about generate about.hbs > LICENSES.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: Update LICENSES.md"
          file_pattern: LICENSES.md
